### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [hayleencc/ISII-WORKSHOPS-Empresa_De_Seguridad#3]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by hayleencc** [comment]
I'm glad to read that, i'm going to give the advice to all the members of the team. We will let you know when it is ready.

**Comment by hayleencc** [comment]
We are moving forward with your problem, now it is categorized to give you a solution as soon as possible.

**Comment by hayleencc** [comment]
We will proceed to process the request, @milenortegam will be the assigned analyst, @ispovala will develop the solution and @Adagmari will eprform the tests

**Comment by jose598** [comment]
Thank you @hayleencc. I'm waiting for you response

**Comment by milenortegam** [comment]
[Impact analysis - Empresa de Seguridad.docx](https://github.com/hayleencc/ISII-WORKSHOPS-Empresa_De_Seguridad/files/7892327/Impact.analysis.-.Empresa.de.Seguridad.docx)
@jose598 Hi, I have attach the document with the impact analysis. We will be waiting for your feedback.

**Comment by jose598** [comment]
Hi @milenortegam  I got it that you won't use our company computers, even it's awesome because we don't need to stop services. However, I don't know what you do it on lines specified in the attached document. So, I will like to take a look at how you are calculating the insurance total, it means that I want to see a table(optional) with all cases/rules applied.

**Comment by milenortegam** [comment]
Hi @jose598 I've considered your suggestions and modified the analysis document. Please check it and let me know if it is correct, thanks.
[Impact analysis - Empresa de Seguridad.docx](https://github.com/hayleencc/ISII-WORKSHOPS-Empresa_De_Seguridad/files/7908525/Impact.analysis.-.Empresa.de.Seguridad.docx)

**Comment by jose598** [comment]
Ok, you can start working on it.

**Comment by ispovala** [comment]
The new rules were implemented between lines 131 and 136:

https://github.com/hayleencc/ISII-WORKSHOPS-Empresa_De_Seguridad/blob/40a9f8896737f1f7b3adc0cb99e459281d39ee89/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L123-L143

**Comment by Adagmari** [comment]
Hi @jose598, the test of the new rules was carried out. Attached to the document  with the test plan for your review.  
[Testing-Empresa de Seguridad.docx](https://github.com/hayleencc/ISII-WORKSHOPS-Empresa_De_Seguridad/files/7915446/Testing-Empresa.de.Seguridad.docx)

**Comment by jose598** [comment]
@Adagmari I have an observation, the first rules when I mentioned that if customer is married, 30<age<60 the disccout for the customer is about $100, because is $50 for each one.

**Comment by ispovala** [comment]
I think you meant "in each case". However now I understand your point and I will proceed to make the correction immediately.

**Comment by jose598** [comment]
@ispovala no worry, it's fine

**Comment by ispovala** [comment]
@jose598  I have replaced the $50 discount with a $100 discount.
Let us know if this is correct.

https://github.com/hayleencc/ISII-WORKSHOPS-Empresa_De_Seguridad/blob/341e41e47622de8faadabef448a80c1a64cbf9fc/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L131-L136

@Adagmari

**Comment by Adagmari** [comment]
@jose598  once the correction has been made. Attached to the document with the test plan for your review.
[Testing-Empresa de Seguridad.docx](https://github.com/hayleencc/ISII-WORKSHOPS-Empresa_De_Seguridad/files/7917153/Testing-Empresa.de.Seguridad.docx)

**Comment by jose598** [comment]
Thank you. I already approved your changes and everything is ok. 
Please, close this issue
